### ISSUE TITLE
What input should I give for ITER_MAX : 

### ISSUE THREAD

**Issue by pratiksan45** [danny311296/Image-Cryptography#1]
Please reply

**Comment by dannyi96** [comment]
This repo ( which was actually a small assignment) was done a long time ago. 
It is an integer denoting how many iterations were done for encrypting / needed for decrypting.
These values are currently harcoded to 1 in `encrypt.py`
`ITER_MAX = 1`
Also from Readme"
"The keys generated during encryption is stored in the keys.txt file.
(Note: The number of iterations of encryption to be performed can be adjusted by changing the ITER_MAX value in the encrypt.py file. Larger values will make encryption more secure but it is more time consuming)"

**Comment by dannyi96** [comment]
It would be nice if these things were parameterised. Feel free to take it up if you would like to work on the same.
